const SEARCH_CASES_LOADING = "SEARCH_CASES_LOADING";
const SEARCH_CASES_DATA_SUCCESS = "SEARCH_CASES_DATA_SUCCESS";
const SEARCH_CASES_DATA_ERROR = "SEARCH_CASES_DATA_ERROR";

export {
  SEARCH_CASES_LOADING,
  SEARCH_CASES_DATA_SUCCESS,
  SEARCH_CASES_DATA_ERROR,
};
